---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    #- MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

install:
  - pip3 install docker==3.4.1
  - pip3 install molecule yamllint ansible-lint

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notification
